# Generated by Django 5.0.1 on 2024-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(),
        ),
    ]
